apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    helm:
      valueFiles:
        - manifest/prometheus/values.yaml
    path: personal-charts/chart/prometheus
    repoURL: https://github.com/abdullah-jaffer/helm-charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

